server:
  port: 8085

spring:
  application:
    name: CONFIG-SERVE

  cloud:
    config:
      server:
        git:
          uri: https://github.com/AnkitaK1998/microservices-config-server
          clone-on-start: true




