server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/micro_hotelservice
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: HOTEL-SERVICE


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/




#okta config
okta:
  oauth2:
    issuer: https://dev-97292499.okta.com/oauth2/default
    audience: api://default